fail_fast: true

repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: >
          (?x)^(
              package-lock\.json
          )$
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key

  # api - Lint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Conventional Commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # TOML
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
        files: pyproject.toml

  # Bash
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        exclude: contrib

  # Dockerfile
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker
        args: ["--ignore=DL3013"]

  # ui - openapi
  - repo: local
    hooks:
      - id: ui-biome
        name: UI - biome
        entry: sh -c 'cd ui && pnpm run check'
        language: system
        files: ^ui/.*\.(js|jsx|ts|tsx|json|css)$
        exclude: (openapi\.json$|openapi-client/)
        pass_filenames: false

      - id: ui-tsc
        name: UI - tsc
        entry: sh -c 'cd ui && pnpm run tsc'
        language: system
        files: ^ui/.*\.(ts|tsx)$
        exclude: ^ui/\.next/
        pass_filenames: false

      - id: generate-openapi-schema
        name: UI - generate OpenAPI schema
        entry: sh -c 'cd api && uv run python -m commands.generate_openapi_schema'
        language: system
        files: (main\.py$|schemas\.py$|pyproject\.toml)
        pass_filenames: false

      - id: generate-frontend-client
        name: UI - generate frontend client
        entry: sh -c 'cd ui && pnpm run generate-client'
        language: system
        files: openapi\.json$
        pass_filenames: false
