fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: >
          (?x)^(
              package-lock\.json
          )$
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
        files: pyproject.toml

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        exclude: contrib

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker
        args: ["--ignore=DL3013"]

  - repo: local
    hooks:
      - id: frontend-biome
        name: run frontend biome
        entry: sh -c 'cd nextjs-frontend && pnpm run check'
        language: system
        types: [file]
        files: ^nextjs-frontend/.*\.(js|jsx|ts|tsx|json|css)$
        exclude: (openapi\.json$|openapi-client/)
        pass_filenames: false
      - id: frontend-tsc
        name: run frontend tsc
        entry: sh -c 'cd nextjs-frontend && pnpm run tsc'
        language: system
        types: [file]
        files: ^nextjs-frontend/.*\.(ts|tsx)$
        pass_filenames: false
      - id: generate-openapi-schema
        name: generate OpenAPI schema
        entry: sh -c 'cd fastapi_backend && uv run python -m commands.generate_openapi_schema'
        language: system
        # Only run OpenAPI schema generation if schemas.py, main.py or package version have changed:
        files: (main\.py$|schemas\.py$|pyproject\.toml)
        pass_filenames: false
      - id: generate-frontend-client
        name: generate frontend client
        entry: sh -c 'cd nextjs-frontend && pnpm run generate-client'
        language: system
        # Only run frontend client generation if frontend files have changed:
        files: openapi\.json$
        pass_filenames: false
