fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: >
          (?x)^(
              package-lock\.json
          )$
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
        files: pyproject.toml

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        exclude: contrib

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint
        args: ["--ignore=DL3013"]

  - repo: local
    hooks:
      - id: ui-biome
        name: run ui biome
        entry: sh -c 'docker compose run --rm --no-deps -T ui pnpm biome check --write --no-errors-on-unmatched --files-ignore-unknown=true'
        language: system
        types: [file]
        files: ^ui/.*\.(js|jsx|ts|tsx|json|css)$
        exclude: (openapi\.json$|openapi-client/)
        pass_filenames: true
      - id: generate-openapi-schema
        name: generate OpenAPI schema
        entry: sh -c 'docker compose run --rm --no-deps -T api uv run python -m commands.generate_openapi_schema'
        language: system
        # Only run OpenAPI schema generation if schemas.py, main.py or package version have changed:
        files: (main\.py$|schemas\.py$|pyproject\.toml)
        pass_filenames: false
      - id: generate-frontend-client
        name: generate frontend client
        entry: sh -c 'docker compose run --rm --no-deps -T ui pnpm run generate-client'
        language: system
        # Only run frontend client generation if frontend files have changed:
        files: ^local-shared-data/openapi\.json$
        pass_filenames: false
