services:
  api:
    hostname: api-dev
    build:
      context: api
      target: dev
    environment:
      - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/mydatabase
      - TEST_DATABASE_URL=postgresql+asyncpg://postgres:password@db_test:5432/testdatabase
      - MAIL_SERVER=mailhog
    ports:
      - "8001:8001"
    networks:
      - my_network
    volumes:
      - ./api:/app
      - fastapi-venv:/app/.venv
      - ./local-shared-data:/app/shared-data
    depends_on:
      - db
  db:
    hostname: db-dev
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db_test:
    hostname: db-test-dev
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdatabase
    ports:
      - "5433:5432"
    networks:
      - my_network
    restart: always
  ui:
    hostname: ui-dev
    build:
      context: ./ui
      target: dev
    user: node
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      NODE_ENV: development
      API_BASE_URL: http://api:8001
      OPENAPI_OUTPUT_FILE: ./shared-data/openapi.json
    volumes:
      - ./ui:/app
      - nextjs-node-modules:/app/node_modules
      - ./local-shared-data:/app/shared-data
  mailhog:
    hostname: mailhog-dev
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - my_network

volumes:
  postgres_data:
  nextjs-node-modules:
  fastapi-venv:

networks:
  my_network:
    driver: bridge
