name: Coveralls Finished

on:
  workflow_run:
    workflows: ["API Tests", "UI Tests"]
    types:
      - completed

jobs:
  finish:
    name: Finish Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
